title: Chen's Homepage
page-top-title: Feiyang Chen
top-section-bg-text: Information Engineering
home-subtitle: Feiyang Chen&ensp;|&ensp;陈飞扬
copyright-text: '&copy; Sen Li 2023-2025. All Rights Reserved.'