title: Feiyang Chen | 陈飞扬
page-top-title: Feiyang Chen
top-section-bg-text: Information Engineering
home-subtitle: 'Feiyang Chen <span class="name-chinese" lang="zh-CN">陈飞扬</span>'
copyright-text: '© Feiyang Chen 2026'
